### ISSUE TITLE
Stopwatch broken?

### ISSUE THREAD

**Issue by davidblurton** [alexis-philip/Casio-F-91W#1]
I can't get the stopwatch to work on the online demo

**Comment by alexisphilip** [comment]
Hi :) Here we are, two years later, it's fixed. The stopwatch/alarm/date time setting were never programmed, you could just switch between the menus. I got back to this project yesterday and finished it. Everything works now!
I added dynamic instructions next to the button, which are now more user friendly. I also created a whole new code structure, which is enjoyable to use.
Have fun :)
